trigger: 'none' # will disable CI builds entirely

pool:
  vmImage: 'windows-2019'
    
variables:
  BuildConfiguration: release
  
steps:

- task: UseDotNet@2
  displayName: Install .NET 6 sdk
  inputs:
    packageType: sdk
    version: 6.0.x
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages
  inputs:
    command: restore
    projects: '**/WebApp.csproj'

- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonar-sc'
    scannerMode: 'MSBuild'
    projectKey: 'azuredevopsCiprojects_azuredevopsCiprojects_AYIXrCdXCy3v8RrQpD8I'
    projectName: 'dotnetproject'
- task: DotNetCoreCLI@2
  displayName: Build Web App
  inputs:
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: SonarQubeAnalyze@5
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*UnitTest*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Create Web App Package (.zip)
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact (WebApp.zip)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'